receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  logging:
    loglevel: debug
  debug:
    verbosity: detailed
  datadog:
    api:
      key: REPLACE
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 30s
processors:
  decouple:
    max_queue_size: 5
  resource:
    attributes:
    - key: env
      value: "lambda_otel"
      action: upsert
  batch:
    timeout: 30s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, decouple]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      exporters: [logging]
  telemetry:
    logs:
      level: "debug"